# Generated by Django 5.2.1 on 2025-05-20 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HscAdmissionScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_roll', models.IntegerField(unique=True)),
                ('class_roll', models.IntegerField(unique=True)),
                ('merit_position', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('birth_certificate_no', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20)),
                ('photo', models.ImageField(upload_to='hsc_science/')),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='Bangladesh', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Admissions.hscadmissionscience')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_board', models.CharField(max_length=50)),
                ('ssc_year', models.IntegerField()),
                ('ssc_gpa', models.FloatField()),
                ('ssc_certificate', models.FileField(blank=True, upload_to='hsc_science/certificates/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='Admissions.hscadmissionscience')),
            ],
        ),
        migrations.AddField(
            model_name='hscadmissionscience',
            name='hsc_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admissions.hscsession'),
        ),
        migrations.CreateModel(
            name='HscAdmissionCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_roll', models.IntegerField(unique=True)),
                ('class_roll', models.IntegerField(unique=True)),
                ('merit_position', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('birth_certificate_no', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20)),
                ('photo', models.ImageField(upload_to='hsc_commerce/')),
                ('hsc_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admissions.hscsession')),
            ],
        ),
        migrations.CreateModel(
            name='HscAdmissionArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_roll', models.IntegerField(unique=True)),
                ('class_roll', models.IntegerField(unique=True)),
                ('merit_position', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('birth_certificate_no', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20)),
                ('photo', models.ImageField(upload_to='hsc_arts/')),
                ('hsc_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admissions.hscsession')),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name_english', models.CharField(max_length=100)),
                ('fathers_nid', models.CharField(max_length=17, unique=True)),
                ('fathers_date_of_birth', models.DateField()),
                ('fathers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('father_occupation', models.CharField(max_length=50)),
                ('fathers_monthly_income', models.IntegerField()),
                ('mother_name_english', models.CharField(max_length=100)),
                ('mothers_nid', models.CharField(max_length=17, unique=True)),
                ('mothers_date_of_birth', models.DateField()),
                ('mothers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('mother_occupation', models.CharField(blank=True, max_length=50)),
                ('mothers_monthly_income', models.IntegerField()),
                ('guardian', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=10)),
                ('guardian_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_date_of_birth', models.DateField(blank=True, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('guardian_nid', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info', to='Admissions.hscadmissionscience')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Admissions.hscadmissionscience')),
            ],
        ),
    ]
