# Generated by Django 5.2.1 on 2025-05-21 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinformation',
            name='ssc_certificate',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='ssc_gpa',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='present_address',
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='compulsory_bangla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compulsory_bangla', to='Admissions.hscsciencesubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='compulsory_english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compulsory_english', to='Admissions.hscsciencesubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='compulsory_ict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compulsory_ict', to='Admissions.hscsciencesubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='elective_chemistry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_chemistry', to='Admissions.hscsciencesubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='elective_physics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_physics', to='Admissions.hscsciencesubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='fourth_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_subject', to='Admissions.hscsciencesubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='main_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_subject', to='Admissions.hscsciencesubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscGpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscInstitution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscReg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscRoll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscSession',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_address_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_policeStation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_postOffice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_wardNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='policeStation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postOffice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='qouta_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='qouta_freedom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='wardNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='ssc_board',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Jessore', 'Jessore'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='ssc_year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
