# Generated by Django 5.2.1 on 2025-05-28 04:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInformationArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_board', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Jessore', 'Jessore'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical'), ('Others', 'Others')], max_length=20)),
                ('ssc_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4)),
                ('sscInstitution', models.CharField(blank=True, max_length=100, null=True)),
                ('sscRoll', models.IntegerField(blank=True, null=True)),
                ('sscReg', models.IntegerField(blank=True, null=True)),
                ('sscGpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInformationCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_board', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Jessore', 'Jessore'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical'), ('Others', 'Others')], max_length=20)),
                ('ssc_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4)),
                ('sscInstitution', models.CharField(blank=True, max_length=100, null=True)),
                ('sscRoll', models.IntegerField(blank=True, null=True)),
                ('sscReg', models.IntegerField(blank=True, null=True)),
                ('sscGpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardNo', models.IntegerField(blank=True, null=True)),
                ('postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.IntegerField()),
                ('permanent_address_same', models.BooleanField(default=False)),
                ('permanent_wardNo', models.IntegerField(blank=True, null=True)),
                ('permanent_postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_postal_code', models.IntegerField(blank=True, null=True)),
                ('qouta_freedom', models.BooleanField(default=False)),
                ('qouta_community', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AddressCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardNo', models.IntegerField(blank=True, null=True)),
                ('postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.IntegerField()),
                ('permanent_address_same', models.BooleanField(default=False)),
                ('permanent_wardNo', models.IntegerField(blank=True, null=True)),
                ('permanent_postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_postal_code', models.IntegerField(blank=True, null=True)),
                ('qouta_freedom', models.BooleanField(default=False)),
                ('qouta_community', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.feepurpose')),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsCompulsorySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsFourthSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsMainSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsOptionalSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceCompulsorySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceFourthSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceMainSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceOptionalSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceCompulsorySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceFourthSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceMainSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceOptionalSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscSessionForPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfoArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name_english', models.CharField(max_length=100)),
                ('fathers_nid', models.CharField(max_length=17, unique=True)),
                ('fathers_date_of_birth', models.DateField()),
                ('fathers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('father_occupation', models.CharField(max_length=50)),
                ('fathers_monthly_income', models.IntegerField()),
                ('mother_name_english', models.CharField(max_length=100)),
                ('mothers_nid', models.CharField(max_length=17, unique=True)),
                ('mothers_date_of_birth', models.DateField()),
                ('mothers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('mother_occupation', models.CharField(blank=True, max_length=50)),
                ('mothers_monthly_income', models.IntegerField()),
                ('guardian', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=10)),
                ('guardian_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_date_of_birth', models.DateField(blank=True, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('guardian_nid', models.CharField(blank=True, max_length=17, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfoCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name_english', models.CharField(max_length=100)),
                ('fathers_nid', models.CharField(max_length=17, unique=True)),
                ('fathers_date_of_birth', models.DateField()),
                ('fathers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('father_occupation', models.CharField(max_length=50)),
                ('fathers_monthly_income', models.IntegerField()),
                ('mother_name_english', models.CharField(max_length=100)),
                ('mothers_nid', models.CharField(max_length=17, unique=True)),
                ('mothers_date_of_birth', models.DateField()),
                ('mothers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('mother_occupation', models.CharField(blank=True, max_length=50)),
                ('mothers_monthly_income', models.IntegerField()),
                ('guardian', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=10)),
                ('guardian_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_date_of_birth', models.DateField(blank=True, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('guardian_nid', models.CharField(blank=True, max_length=17, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SscSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HscArtsSubjects',
        ),
        migrations.DeleteModel(
            name='HscCommerceSubjects',
        ),
        migrations.DeleteModel(
            name='HscScienceSubjects',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='ssc_certificate',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='ssc_gpa',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='present_address',
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscGpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscInstitution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscReg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='sscRoll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_address_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_policeStation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_postOffice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_wardNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='policeStation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postOffice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='qouta_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='qouta_freedom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='wardNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissionarts',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissionarts',
            name='program',
            field=models.CharField(default='HSC', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='hscadmissionarts',
            name='type',
            field=models.CharField(default='Humanities', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='hscadmissioncommerce',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissioncommerce',
            name='program',
            field=models.CharField(default='HSC', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='hscadmissioncommerce',
            name='type',
            field=models.CharField(default='Business', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='hscadmissionscience',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissionscience',
            name='program',
            field=models.CharField(default='HSC', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='hscadmissionscience',
            name='type',
            field=models.CharField(default='Science', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='ssc_board',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Jessore', 'Jessore'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='ssc_year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hscadmissionarts',
            name='photo',
            field=models.ImageField(upload_to='hsc-arts/'),
        ),
        migrations.AlterField(
            model_name='hscadmissioncommerce',
            name='photo',
            field=models.ImageField(upload_to='hsc-commerce/'),
        ),
        migrations.AlterField(
            model_name='hscadmissionscience',
            name='photo',
            field=models.ImageField(upload_to='hsc-science/'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info_arts', to='Admissions.hscadmissionarts'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info_commerce', to='Admissions.hscadmissioncommerce'),
        ),
        migrations.AddField(
            model_name='addressarts',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_arts', to='Admissions.hscadmissionarts'),
        ),
        migrations.AddField(
            model_name='addresscommerce',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_commerce', to='Admissions.hscadmissioncommerce'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='compulsorySubjects',
            field=models.ManyToManyField(related_name='academic_infos_compulsory_arts', to='Admissions.hscartscompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='FourSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_four_arts', to='Admissions.hscartsfourthsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='mainSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_main_arts', to='Admissions.hscartsmainsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='optionalSubjects',
            field=models.ManyToManyField(related_name='academic_infos_optional_arts', to='Admissions.hscartsoptionalsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='compulsorySubjects',
            field=models.ManyToManyField(related_name='academic_infos_compulsory_commerce', to='Admissions.hsccommercecompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='FourSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_four_commerce', to='Admissions.hsccommercefourthsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='mainSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_main_commerce', to='Admissions.hsccommercemainsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='optionalSubjects',
            field=models.ManyToManyField(related_name='academic_infos_optional_commerce', to='Admissions.hsccommerceoptionalsubjects'),
        ),
        migrations.AddField(
            model_name='hscsession',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hsc_sessions_fee', to='Admissions.hscfeetype'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='compulsorySubjects',
            field=models.ManyToManyField(related_name='academic_infos_compulsory', to='Admissions.hscsciencecompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='FourSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_four', to='Admissions.hscsciencefourthsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='mainSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_main', to='Admissions.hscsciencemainsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='optionalSubjects',
            field=models.ManyToManyField(related_name='academic_infos_optional', to='Admissions.hscscienceoptionalsubjects'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='hsc_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.hscsessionforpayment'),
        ),
        migrations.AlterField(
            model_name='hscadmissionscience',
            name='hsc_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admissions.hscsessionforpayment'),
        ),
        migrations.AddField(
            model_name='parentinfoarts',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info_arts', to='Admissions.hscadmissionarts'),
        ),
        migrations.AddField(
            model_name='parentinfocommerce',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info_commerce', to='Admissions.hscadmissioncommerce'),
        ),
        migrations.AddField(
            model_name='paymentarts',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_arts', to='Admissions.hscadmissionarts'),
        ),
        migrations.AddField(
            model_name='paymentcommerce',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_commerce', to='Admissions.hscadmissioncommerce'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Admissions.programtype'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.programtype'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='ssc_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_commerce', to='Admissions.sscsession'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='ssc_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_arts', to='Admissions.sscsession'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='ssc_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_ssc_session_science', to='Admissions.sscsession'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('program_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('hsc_session', 'program_type', 'program', 'fee_purpose')},
        ),
    ]
