# Generated by Django 5.2.1 on 2025-05-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0002_remove_academicinformation_ssc_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscsciencesubjects',
            name='fourth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hscsciencesubjects',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hscsciencesubjects',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hscadmissionarts',
            name='photo',
            field=models.ImageField(upload_to='hsc-arts/'),
        ),
        migrations.AlterField(
            model_name='hscadmissioncommerce',
            name='photo',
            field=models.ImageField(upload_to='hsc-commerce/'),
        ),
        migrations.AlterField(
            model_name='hscadmissionscience',
            name='photo',
            field=models.ImageField(upload_to='hsc-science/'),
        ),
    ]
