# Generated by Django 5.2.1 on 2025-05-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0003_hscsciencesubjects_fourth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SscSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='sscSession',
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='ssc_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos', to='Admissions.sscsession'),
        ),
    ]
