# Generated by Django 5.2.1 on 2025-05-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0004_sscsession_remove_academicinformation_sscsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscsession',
            name='admission_fee',
            field=models.IntegerField(default=0),
        ),
    ]
