# Generated by Django 5.2.1 on 2025-05-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0005_hscsession_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscsciencesubjects',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
