# Generated by Django 5.2.1 on 2025-05-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0006_hscsciencesubjects_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscsciencesubjects',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
