# Generated by Django 5.2.1 on 2025-05-26 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0007_hscsciencesubjects_is_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='HscScienceCompulsorySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceFourthSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceMainSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscScienceOptionalSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='compulsory_bangla',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='elective_physics',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='fourth_subject',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='compulsory_ict',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='elective_chemistry',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='compulsory_english',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='main_subject',
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='FourSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_four', to='Admissions.hscsciencecompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='compulsorySubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_compulsory', to='Admissions.hscsciencecompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='mainSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_main', to='Admissions.hscsciencecompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='optionalSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_optional', to='Admissions.hscsciencecompulsorysubjects'),
        ),
        migrations.DeleteModel(
            name='HscScienceSubjects',
        ),
    ]
