# Generated by Django 5.2.1 on 2025-05-26 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0008_hscsciencecompulsorysubjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HscFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hscsession',
            name='admission_fee',
        ),
        migrations.AddField(
            model_name='hscsession',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hsc_sessions', to='Admissions.hscfeetype'),
        ),
    ]
