# Generated by Django 5.2.1 on 2025-05-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0009_hscfeetype_remove_hscsession_admission_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinformation',
            name='FourSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_four', to='Admissions.hscsciencefourthsubjects'),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='mainSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_main', to='Admissions.hscsciencemainsubjects'),
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='optionalSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_optional', to='Admissions.hscscienceoptionalsubjects'),
        ),
    ]
