# Generated by Django 5.2.1 on 2025-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0010_alter_academicinformation_foursubjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinformation',
            name='compulsorySubjects',
        ),
        migrations.RemoveField(
            model_name='academicinformation',
            name='optionalSubjects',
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='compulsorySubjects',
            field=models.ManyToManyField(related_name='academic_infos_compulsory', to='Admissions.hscsciencecompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformation',
            name='optionalSubjects',
            field=models.ManyToManyField(related_name='academic_infos_optional', to='Admissions.hscscienceoptionalsubjects'),
        ),
    ]
