# Generated by Django 5.2.1 on 2025-05-27 06:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0011_remove_academicinformation_compulsorysubjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInformationArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_board', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Jessore', 'Jessore'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical'), ('Others', 'Others')], max_length=20)),
                ('ssc_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4)),
                ('sscInstitution', models.CharField(blank=True, max_length=100, null=True)),
                ('sscRoll', models.IntegerField(blank=True, null=True)),
                ('sscReg', models.IntegerField(blank=True, null=True)),
                ('sscGpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ssc_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_arts', to='Admissions.sscsession')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info_arts', to='Admissions.hscadmissionarts')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInformationCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_board', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Jessore', 'Jessore'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical'), ('Others', 'Others')], max_length=20)),
                ('ssc_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4)),
                ('sscInstitution', models.CharField(blank=True, max_length=100, null=True)),
                ('sscRoll', models.IntegerField(blank=True, null=True)),
                ('sscReg', models.IntegerField(blank=True, null=True)),
                ('sscGpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ssc_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_commerce', to='Admissions.sscsession')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info_commerce', to='Admissions.hscadmissioncommerce')),
            ],
        ),
        migrations.CreateModel(
            name='AddressArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardNo', models.IntegerField(blank=True, null=True)),
                ('postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.IntegerField()),
                ('permanent_address_same', models.BooleanField(default=False)),
                ('permanent_wardNo', models.IntegerField(blank=True, null=True)),
                ('permanent_postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_postal_code', models.IntegerField(blank=True, null=True)),
                ('qouta_freedom', models.BooleanField(default=False)),
                ('qouta_community', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_arts', to='Admissions.hscadmissionarts')),
            ],
        ),
        migrations.CreateModel(
            name='AddressCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardNo', models.IntegerField(blank=True, null=True)),
                ('postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.IntegerField()),
                ('permanent_address_same', models.BooleanField(default=False)),
                ('permanent_wardNo', models.IntegerField(blank=True, null=True)),
                ('permanent_postOffice', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_policeStation', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_postal_code', models.IntegerField(blank=True, null=True)),
                ('qouta_freedom', models.BooleanField(default=False)),
                ('qouta_community', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_commerce', to='Admissions.hscadmissioncommerce')),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsCompulsorySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsFourthSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsMainSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscArtsOptionalSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceCompulsorySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceFourthSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceMainSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscCommerceOptionalSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfoArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name_english', models.CharField(max_length=100)),
                ('fathers_nid', models.CharField(max_length=17, unique=True)),
                ('fathers_date_of_birth', models.DateField()),
                ('fathers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('father_occupation', models.CharField(max_length=50)),
                ('fathers_monthly_income', models.IntegerField()),
                ('mother_name_english', models.CharField(max_length=100)),
                ('mothers_nid', models.CharField(max_length=17, unique=True)),
                ('mothers_date_of_birth', models.DateField()),
                ('mothers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('mother_occupation', models.CharField(blank=True, max_length=50)),
                ('mothers_monthly_income', models.IntegerField()),
                ('guardian', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=10)),
                ('guardian_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_date_of_birth', models.DateField(blank=True, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('guardian_nid', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info_arts', to='Admissions.hscadmissionarts')),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfoCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name_english', models.CharField(max_length=100)),
                ('fathers_nid', models.CharField(max_length=17, unique=True)),
                ('fathers_date_of_birth', models.DateField()),
                ('fathers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('father_occupation', models.CharField(max_length=50)),
                ('fathers_monthly_income', models.IntegerField()),
                ('mother_name_english', models.CharField(max_length=100)),
                ('mothers_nid', models.CharField(max_length=17, unique=True)),
                ('mothers_date_of_birth', models.DateField()),
                ('mothers_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('mother_occupation', models.CharField(blank=True, max_length=50)),
                ('mothers_monthly_income', models.IntegerField()),
                ('guardian', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=10)),
                ('guardian_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_date_of_birth', models.DateField(blank=True, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid 11-digit number.')])),
                ('guardian_nid', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info_commerce', to='Admissions.hscadmissioncommerce')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentArts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_arts', to='Admissions.hscadmissionarts')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_commerce', to='Admissions.hscadmissioncommerce')),
            ],
        ),
        migrations.DeleteModel(
            name='HscArtsSubjects',
        ),
        migrations.DeleteModel(
            name='HscCommerceSubjects',
        ),
        migrations.AlterField(
            model_name='academicinformation',
            name='ssc_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_ssc_session_science', to='Admissions.sscsession'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='compulsorySubjects',
            field=models.ManyToManyField(related_name='academic_infos_compulsory_arts', to='Admissions.hscartscompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='FourSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_four_arts', to='Admissions.hscartsfourthsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='mainSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_main_arts', to='Admissions.hscartsmainsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationarts',
            name='optionalSubjects',
            field=models.ManyToManyField(related_name='academic_infos_optional_arts', to='Admissions.hscartsoptionalsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='compulsorySubjects',
            field=models.ManyToManyField(related_name='academic_infos_compulsory_commerce', to='Admissions.hsccommercecompulsorysubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='FourSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_four_commerce', to='Admissions.hsccommercefourthsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='mainSubjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_infos_main_commerce', to='Admissions.hsccommercemainsubjects'),
        ),
        migrations.AddField(
            model_name='academicinformationcommerce',
            name='optionalSubjects',
            field=models.ManyToManyField(related_name='academic_infos_optional_commerce', to='Admissions.hsccommerceoptionalsubjects'),
        ),
    ]
