# Generated by Django 5.2.1 on 2025-05-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0012_academicinformationarts_academicinformationcommerce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissionarts',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissioncommerce',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hscadmissionscience',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
