# Generated by Django 5.2.1 on 2025-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0013_hscadmissionarts_name_bangla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissionarts',
            name='type',
            field=models.CharField(default='Humanities', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='hscadmissioncommerce',
            name='type',
            field=models.CharField(default='Business', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='hscadmissionscience',
            name='type',
            field=models.CharField(default='Science', editable=False, max_length=10),
        ),
    ]
