# Generated by Django 5.2.1 on 2025-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0014_hscadmissionarts_type_hscadmissioncommerce_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscadmissionarts',
            name='program',
            field=models.CharField(default='HSC', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='hscadmissioncommerce',
            name='program',
            field=models.CharField(default='HSC', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='hscadmissionscience',
            name='program',
            field=models.CharField(default='HSC', editable=False, max_length=20),
        ),
    ]
