# Generated by Django 5.2.1 on 2025-05-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0015_hscadmissionarts_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HscSessionForPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hscsession',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hsc_sessions_fee', to='Admissions.hscfeetype'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Admissions.programtype')),
            ],
            options={
                'unique_together': {('program_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.feepurpose')),
                ('hsc_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.hscsessionforpayment')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.program')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Admissions.programtype')),
            ],
            options={
                'unique_together': {('hsc_session', 'program_type', 'program', 'fee_purpose')},
            },
        ),
    ]
