# Generated by Django 5.2.1 on 2025-05-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0016_feepurpose_hscsessionforpayment_programtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscadmissionscience',
            name='hsc_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admissions.hscsessionforpayment'),
        ),
    ]
