# Generated by Django 5.2.1 on 2025-05-28 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Exams.examlevel')),
            ],
            options={
                'unique_together': {('exam_level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Exams.examlevel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Exams.group')),
            ],
            options={
                'unique_together': {('exam_level', 'group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('exam_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Exams.examlevel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Exams.group')),
                ('subjects', models.ManyToManyField(blank=True, related_name='exams', to='Exams.subject')),
            ],
        ),
    ]
