# Generated by Django 5.2.1 on 2025-05-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='institution_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notice_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notice_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notice_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
