# Generated by Django 5.2.1 on 2025-05-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0002_notice_sitesettings_favicon_sitesettings_footer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_description',
        ),
    ]
