# Generated by Django 5.2.1 on 2025-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0002_sitesettings_favicon_sitesettings_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_description', models.TextField(blank=True, null=True)),
                ('notice_file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='notice_date',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='notice_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='notice_file',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='notice_title',
        ),
    ]
