# Generated by Django 5.2.1 on 2025-05-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_notice_remove_sitesettings_notice_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='date',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
