# Generated by Django 5.2.1 on 2025-05-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0004_remove_notice_date_notice_notice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_date',
            new_name='date',
        ),
    ]
